export const PRODUCT_REQ = 'PRODUCT_REQ';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAIL = 'PRODUCT_FAIL';

export const PRODUCT_TOTAL_REQ = 'PRODUCT_TOTAL_REQ';
export const PRODUCT_TOTAL_SUCCESS = 'PRODUCT_TOTAL_SUCCESS';
export const PRODUCT_TOTAL_FAIL = 'PRODUCT_TOTAL_FAIL';